//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnLReporter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidence
    {
        public string url { get; set; }
        public string title { get; set; }
        public Nullable<int> transactionVersion { get; set; }
        public string transactionId { get; set; }
        public string description { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
