//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnLReporter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Evidences = new HashSet<Evidence>();
            this.Transaction1 = new HashSet<Transaction>();
        }
    
        public string transactionId { get; set; }
        public int version { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public Nullable<int> status { get; set; }
        public string description { get; set; }
        public string masterTransactionId { get; set; }
        public Nullable<int> masterTransactionVersion { get; set; }
        public Nullable<decimal> categoryId { get; set; }
        public Nullable<decimal> periodId { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public string createdBy { get; set; }
        public string confirmedBy { get; set; }
        public Nullable<System.DateTime> confirmedTime { get; set; }
    
        public virtual AccountingPeriod AccountingPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidence> Evidences { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual Participant Participant1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction1 { get; set; }
        public virtual Transaction Transaction2 { get; set; }
        public virtual TransactionCategory TransactionCategory { get; set; }
    }
}
